### ISSUE TITLE
myStorage.js有问题

### ISSUE THREAD

**Issue by wujunchuan** [phillyx/MUIDemos#3]
我的localstorage存储了这些数据，但是每次获取的都是同一个key的value
![image](https://cloud.githubusercontent.com/assets/7511631/16982263/8eef97f8-4ea1-11e6-93b0-5beb5c66685d.png)
![image](https://cloud.githubusercontent.com/assets/7511631/16982289/a41965c8-4ea1-11e6-8bc8-703d240a765e.png)

**Comment by phillyx** [comment]
key方法时通过index获取的key值，是int类型的数据，不识别string类型，默认就为0，自然是返回0索引的key啊 
具体方法接口参考这http://www.cnblogs.com/phillyx/p/4761364.html

**Comment by wujunchuan** [comment]
好的，谢谢你！
