### ISSUE TITLE
关于定位的一些疑问

### ISSUE THREAD

**Issue by riddle911** [phillyx/MUIDemos#8]
老哥老哥，
定位我按照geolocation那一套东西写好了。也都跑通了。
我的把getcurrentlocation和watchposition分别写了方法，一个是定位到现在位置，一个是开始/停止记录轨迹。

现在问题是，步行的时候吧，watchpositon出来的数据还凑合，然而移动速度快一些，比如坐车上....定位一下子就漂了，没反应.....

不知道您有没有遇到过类似问题。我折腾一周好容易把定位模块写好了，结果不能用....心都碎了.

**Comment by phillyx** [comment]
这个应该是bridge接口，原生的问题，不过在移动的时候建议不要频繁去获取数据，设置一个时间段不间歇访问好一些。

**Comment by riddle911** [comment]
嗯.....大神你是说这个还是他封装接口的问题么。我昨天也试了用setinterval 定时获取，不过效果微乎其微.....
另外也看了官方那个demo，感觉监听的效果也不怎么样....

老哥，我就是想实现基本的地图导航...人走哪定位实时就显示到地图上..用的高德sdk输出坐标然后借助leaflet展示在地图上。这感觉还没有人家纯html5 做的效果好了 。
您说我是不是还得趟原生的坑.......
